# Verification

See which requirements have calculations, which checks fail, and what remains
missing. This notebook uses the same saved vehicle, flight, and departure inputs
as the first two notebooks. A passing calculation does not close a requirement:
closure needs reviewed evidence for every activity and resolved TBD/TBR values.

In [1]:
import pandas as pd
from IPython.display import display, Markdown

from model.inputs import load_checks, input_tables, choices_table
from model.notebook import show_input_tables, show_table
from model.workspace import current_flight
from model.verification import activities, evaluate, requirement_status
from model.outputs import input_identity, save_verification

## 1. Inputs

[vehicle.toml](inputs/vehicle.toml) and [flight.toml](inputs/flight.toml) define the
shared simulation. [checks.toml](inputs/checks.toml) defines analysis inputs,
limits, and their sources. An activity-specific entry takes precedence over a
shared calculation entry. [requirements](inputs/requirements/) preserve the
imported statements; [evidence](inputs/evidence/) holds supplied review records.

The selection below only changes which rows are displayed; every activity is
still evaluated and exported.

In [2]:
REQUIREMENT = "PERF.2.13"
REQUIREMENT_PREFIX = "AVI.3.COM"

run_inputs = input_identity()
checks = load_checks()
register = activities()
print(f"Imported {register.requirement_id.nunique()} requirements and {len(register)} activities.")

rules = []
for entry, specification in checks.items():
    for rule in specification.get("acceptance", []):
        rules.append({
            "Applies to": entry, "Metric": rule["metric"],
            "Rule": rule["operator"], "Limit": rule["limit"],
            "Units": rule["units"], "Source": rule["source"],
        })
show_table(pd.DataFrame(rules))
show_input_tables(input_tables())

Imported 373 requirements and 677 activities.

## 2. Choices and assumptions

| Result | Meaning | Next step |
|---|---|---|
| `SCREEN_PASS` | Calculation meets the supplied limit | Validate assumptions and review evidence |
| `SCREEN_FAIL` | Calculation misses the supplied limit | Review the design, inputs, and limit |
| `CALCULATED` | Result has no acceptance rule | Supply an approved limit and source |
| `MISSING_INPUTS` | Calculation needs more data | Supply the named inputs |
| `EVIDENCE_REQUIRED` | Test, inspection, or analysis record is missing | Add the reviewed evidence |
| `INVALID_INPUTS` / `INVALID_EVIDENCE` | Data or record cannot be used | Fix the stated issue |
| `STALE_EVIDENCE` | Record refers to older inputs or wording | Review it against the current version |

Demonstration data are not vehicle verification evidence. The choices below
remain part of the basis for every simulation-derived result.

In [3]:
show_table(choices_table())

## 3. Run

This evaluates the full register. It reuses the current ascent and reports
missing inputs or evidence explicitly; it does not fill gaps with example values.

In [4]:
results, details = evaluate(context=current_flight())
requirements = requirement_status(results)

## 4. Outputs

Start with failed checks and unusable records. Full activity and requirement
tables are saved even when only a subset is displayed here.

In [5]:
show_table(results.status.value_counts().rename_axis("Activity result").reset_index(name="Count"))
show_table(requirements.status.value_counts().rename_axis("Requirement result").reset_index(name="Count"))

failure_statuses = ["SCREEN_FAIL", "REVIEWED_FAIL", "INVALID_INPUTS", "INVALID_EVIDENCE"]
failures = results[results.status.isin(failure_statuses)]
columns = {"activity_id": "Activity ID", "activity": "Required work", "status": "Result", "detail": "Basis or issue"}
show_table(failures[list(columns)].rename(columns=columns))

### Selected requirement and subsystem

Read the exact wording, source location, and unresolved values before changing
inputs or attaching evidence. Change the view selections in section 1 to inspect
another requirement or subsystem.

In [6]:
selected = results[results.requirement_id.eq(REQUIREMENT)]
if selected.empty:
    print("No matching requirement. See outputs/current/tables/activities.csv for available IDs.")
else:
    requirement = selected.iloc[0]
    display(Markdown(f"**{REQUIREMENT}:** {requirement['statement']}"))
    print("Source:", requirement["source"])
    print("Unresolved values:", requirement["open_parameters"] or "None listed")
    columns = {
        "activity_id": "Activity ID", "activity": "Required work", "kernel": "Calculation",
        "status": "Result", "detail": "Basis or missing inputs",
    }
    show_table(selected[list(columns)].rename(columns=columns).fillna("External evidence"))

subsystem = results[results.requirement_id.str.startswith(REQUIREMENT_PREFIX)]
print("Subsystem selection:", REQUIREMENT_PREFIX)
show_table(subsystem[["activity_id", "activity", "status", "detail"]].rename(columns={
    "activity_id": "Activity ID", "activity": "Required work", "status": "Result", "detail": "Next input or evidence",
}))

**PERF.2.13:** The LV shall maintain a controllability ratio of at least 2.

Source: 2 LV Performance!H14
Unresolved values: None listed

Subsystem selection: AVI.3.COM

## 5. What to do next

1. Find the activity in the saved [activity table](outputs/current/tables/activity_results.csv).
2. Find its arguments in [calculation_inputs.csv](outputs/current/tables/calculation_inputs.csv).
3. Add sourced inputs and acceptance rules to [checks.toml](inputs/checks.toml).
4. Add reviewed tests, inspections, or specialist analyses using the [evidence guide](inputs/evidence/README.md).
5. Run All again. Read the [summary](outputs/current/summary.md) and [requirement status](outputs/current/tables/requirement_status.csv).

For a requirements revision, follow the [README import steps](README.md).
The importer reads a saved workbook; it does not synchronize or edit OneDrive.
Each export includes the [exact inputs used](outputs/current/inputs_used/).

In [7]:
output_folder = save_verification(results, details, expected_inputs=run_inputs)
print(f"Saved {len(results)} activities and {len(requirements)} requirements to:", output_folder)

Saved 677 activities and 373 requirements to: C:\Users\maxwe\.codex\.chatgpt-projects\g-p-6a9464860c90819188ae3dd3be539576\Hyperion\outputs\current